changelog:
    categories:
        - title: ⚠️ Breaking
          labels:
              - Breaking changes
        - title: New
          labels:
              - Component
              - Pattern
        - title: Enhancements
          labels:
              - Enhancement
        - title: Fixes
          labels:
              - Bug
        - title: Accessibility
          labels:
              - Accessibility
        - title: Documentation
          labels:
              - Documentation
              - Example
        - title: Build & tooling
          labels:
              - Dependencies
              - CI/CD
              - Tech improvements
        - title: Other
          labels:
              - '*'
