files:
  include: "**/*.s+(a|c)ss"
options:
  formatter: stylish
  merge-default-rules: false
rules:
  bem-depth: 1
  border-zero:
    - 1
    - convention: zero
  brace-style:
    - 1
    - allow-single-line: false
  class-name-format:
    - 1
    - convention: ^(?!js-).*
      convention-explanation: should not be written in the form js-*
  extends-before-declarations: 1
  extends-before-mixins: 1
  function-name-format: 1
  id-name-format:
    - 1
    - convention: hyphenatedbem
  indentation:
    - 1
    - size: 2
  leading-zero: 0
  mixin-name-format: 1
  mixins-before-declarations: 1
  no-extends: 0
  no-qualifying-elements: 0
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  placeholder-in-extend: 0
  property-sort-order: 'concentric'
  quotes:
    - 1
    - style: single
  variable-name-format: 1
