defaultSeverity: warning
extends:
    - stylelint-config-standard
    - stylelint-config-recommended
    - stylelint-config-sass-guidelines
plugins:
    - stylelint-scss
    - stylelint-order
rules:
    # Line Spacing
    rule-empty-line-before:
        - always-multi-line
        - ignore:
              - after-comment
              - first-nested
              - inside-block

    # Disallows
    selector-max-id: 2
    comment-no-empty: true
    declaration-block-no-duplicate-properties: true
    block-no-empty:
        - true
        - ignore:
              - comments
    no-descending-specificity: null
    color-no-invalid-hex: true
    length-zero-no-unit: true
    scss/at-extend-no-missing-placeholder: null
    selector-no-qualifying-type:
        - true
        - ignore:
              - attribute
              - class
              - id
    property-no-unknown:
        - true
        - ignoreProperties:
              - 'box-orient'
        - ignoreAtRules: ['each', 'else', 'extend', 'for', 'function', 'if', 'include', 'mixin', 'return', 'while']
    # Imports
    import-notation: 'string'
    # Nesting
    max-nesting-depth:
        - 5
        - ignore: ['blockless-at-rules', 'pseudo-classes']

    # Name Formats
    selector-class-pattern: null
    scss/at-mixin-pattern: null

    # Style Guide
    color-named: 'never'
    unit-no-unknown:
        - true
        - ignoreUnits:
              - /^[-+][\d$(]/
    font-family-no-duplicate-names: true
    selector-max-compound-selectors: 6
    order/order: null

    # Inner Spacing
    function-calc-no-unspaced-operator: true
