platform: linux
image_resource:
  type: docker-image
  source:
    repository: node
    tag: 14.15.0

inputs:
  - name: ons-design-system-release

outputs:
  - name: ds-release-artifacts

run:
  path: sh
  args:
  - -exc
  - |
    apt-get update && apt-get install -y --allow-unauthenticated zip

    cd ons-design-system-release

    mkdir design-system
    tar -xzf source.tar.gz -C design-system --strip-components=1

    cd design-system

    design_system_release=$(cat ../../ons-design-system-release/version)

    yarn
    RELEASE_VERSION=$design_system_release yarn cdn-bundle

    output_path="../../ds-release-artifacts/design-system/$design_system_release"
    mkdir -p $output_path
    cp -R build/* $output_path
