name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['Bug', 'Community backlog', 'High priority']
projects: ONS Design System project
assignees: []
body:
    - type: markdown
      attributes:
          value: |
              Thank you for taking the time to fill out this bug report
    - type: textarea
      id: describe-bug
      attributes:
          label: Describe the bug
          description: 'If applicable, add screenshot(s) or examples of the bug/issue'
      validations:
          required: true
    - type: textarea
      id: expected-behaviour
      attributes:
          label: Expected behaviour / outcome
          description: 'If applicable, add screenshot(s) or examples of the expected behaviour'
      validations:
          required: true
    - type: textarea
      id: reproduction-steps
      attributes:
          label: List the steps necessary to reproduce the bug
      validations:
          required: true
    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
          description: 'For example: describe the severity of the issue, any additional evidence, screenshots, proposed solution'
      validations:
          required: false
    - type: input
      id: version
      attributes:
          label: What version of the ONS Design System are you using?
          description: 'For example: 32.2.7'
      validations:
          required: true
    - type: dropdown
      id: devices
      attributes:
          label: What device(s) are you using?
          options:
              - Desktop
              - Mobile
              - Tablet
          multiple: true
      validations:
          required: true
    - type: dropdown
      id: operating-system
      attributes:
          label: What operating system(s) are you using?
          options:
              - Windows
              - macOS
              - Android
              - iOS
              - Other
          multiple: true
      validations:
          required: true
    - type: dropdown
      id: browsers
      attributes:
          label: What browser(s) are you using?
          options:
              - Firefox
              - Chrome
              - Safari
              - Microsoft Edge
              - Other
          multiple: true
      validations:
          required: true
