resources:

- name: ons-design-system-release
  type: github-release
  source:
    owner: ONSdigital
    repository: design-system

- name: slack-alert
  type: slack-notification
    source: {{slack_webhook_url}}

jobs:
- name: Release
  plan:
  - get: ons-design-system-release
    trigger: true

  - task: CDN Build
    config:
      platform: linux

      image_resource:
        type: docker-image
        source:
          repository: node
          tag: 10.14.2

      inputs:
      - name: ons-design-system-release

      outputs:
      - name: dist

      run:
        path: sh
        args:
        - -exc
        - |
          cd ons-design-system-release
          
          mkdir design-system
          tar -xzf source.tar.gz -C design-system --strip-components=1

          cd design-system

          yarn
          yarn cdn-bundle

          design_system_release=$(cat  ../../ons-design-system-release/version)

          mkdir ../../dist/$design_system_release
          cp -R build/* ../../dist/$design_system_release
    on_failure:
      put: slack-alert
      params:
          channel: '#pat-lib-notifications'
          attachments:
            - pretext: Design System Build Failed
            color: danger
            title: Concourse Build $BUILD_ID
            title_link: http://concourse.dev.eq.ons.digital/builds/$BUILD_ID

  - task: Release to S3
    params: 
      AWS_ACCESS_KEY_ID: {{aws_access_key}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_key}}
      AWS_DEFAULT_REGION: eu-west-1
    config:
      platform: linux

      image_resource:
        type: docker-image
        source:
          repository: mesophere/aws-cli

      inputs:
      - name: dist

      run:
        path: sh
        args:
        - -exc
        - |
          aws s3 sync --acl public-read dist s3://((s3_bucket_name))/design-system/
    on_failure:
      put: slack-alert
      params:
        channel: '#pat-lib-notifications'
        attachments:
          - pretext: Design System CDN Release Failed
            color: danger
            title: Concourse Build $BUILD_ID
            title_link: http://concourse.dev.eq.ons.digital/builds/$BUILD_ID
