name: Checklist Checker
on:
    pull_request:
        types:
            - opened
            - edited
            - synchronize
            - reopened

permissions:
    pull-requests: read

jobs:
    check-tasks:
        runs-on: ubuntu-latest
        if: github.event.pull_request.user.login != 'dependabot[bot]' # ignore pull requests raised by dependabot
        steps:
            - name: Check tasks
              uses: mheap/require-checklist-action@v2
              with:
                  requireChecklist: true
