name: Checklist Checker
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  check-tasks:
    runs-on: ubuntu-latest
    if: github.actor = 'dependabot[bot]' # ignore pull requests that come from dependabot.
    steps:
      - name: Check tasks
        uses: mheap/require-checklist-action@v2
        with:
          requireChecklist: true
