name: Checklist Checker
on:
  pull_request:
    branches-ignore:
        - dependabot/*
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  check-tasks:
    name: Check tasks
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/require-checklist-action@v2
        with:
          requireChecklist: true
