name: Label Checker
on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - labeled
            - unlabeled

jobs:
    check-labels:
        name: Check labels
        runs-on: ubuntu-latest
        permissions:
            pull-requests: read
        steps:
            - uses: docker://onsdigital/github-pr-label-checker:latest
              with:
                  one_of: Accessibility,Bug,Documentation,Dependencies,Enhancement,Example,Component,Pattern,CI/CD,Tech improvements,Breaking changes
                  none_of: Awaiting resource,Do not merge,Duplicate,Needs validating,Not doing
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
