name: Checklist Checker
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  check-tasks:
    if: github.actor == 'dependabot[bot]' # ignore pull requests that come from dependabot.
    steps:
      - name: Check tasks
        runs-on: ubuntu-latest
        steps:
          - uses: mheap/require-checklist-action@v2
            with:
              requireChecklist: true
