name: Release
on:
    release:
        types: [published]

permissions:
    contents: write

jobs:
    add-templates-to-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
              with:
                  ref: ${{ github.event.release.tag_name }}
            - name: Install Node
              uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
              with:
                  node-version-file: '.nvmrc'
            - name: Install dependencies
              run: yarn install
            - name: Build templates
              run: |
                  cd src
                  RELEASE_VERSION=${{ github.event.release.tag_name }} yarn cdn-bundle
            - name: Zip templates
              run: zip -r templates.zip templates/*
            - name: Release
              uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
              with:
                  files: templates.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
