name: 'PR Tasks Completed Check'
on: 
  pull_request:
    types: [opened, edited]
env:
  RUNNING_ON_CI: true
jobs:
  task-check:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/task-completed-checker-action@v0.1.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
