name: PR Tasks Completed Checker
on: 
  pull_request:
    types:
      - opened
      - edited

jobs:

  check-tasks:
    name: Check tasks
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/task-completed-checker-action@v0.1.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
