name: test-workflow
on:
  push:
    branches:
      - test-workflow
  pull_request:
    branches:
      - test-workflow
jobs:
  cdn-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm -v
