name: test-workflow
on:
  push:
    branches:
      - test-workflow
  pull_request:
    branches:
      - test-workflow
jobs:
  cdn-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: apt-get update && apt-get install -y --allow-unauthenticated zip
      - run: cd ons-design-system-release
      - run: mkdir design-system
      - run: tar -xzf source.tar.gz -C design-system --strip-components=1
      - run: cd design-system
      - run: design_system_release=$(cat ../../ons-design-system-release/version)
      - run: yarn
      - run: RELEASE_VERSION=$design_system_release yarn cdn-bundle
      - run: mkdir ../../dist/$design_system_release
      - run: cp -R build/* ../../dist/$design_system_release
      - run: zip -r ../../templates/templates.zip templates/*
