name: Run visual regression tests
on: [push]

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  RUNNING_IN_CI: true

jobs:
  run-visual-regression-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: yarn install
      - name: Install Docker
        run: |
          sudo apt update
          sudo apt remove containerd.io
          sudo apt install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
      - name: Run visual regression tests
        run: yarn test-visual
