name: zip-templates-on-release
on:
  release:
    types: [published]
jobs:
  zip-templates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g yarn
      - run: yarn install
      - run: sudo apt-get update && sudo apt-get install -y --allow-unauthenticated zip
      - run: curl -s https://api.github.com/repos/ONSdigital/design-system/releases/latest | jq -r ".tarball_url" | wget -i - -O source.tar.gz
      - run: mkdir design-system
      - run: tar -xzf source.tar.gz -C design-system --strip-components=1
      - run: cd design-system
      - run: design_system_release=$(curl -s https://api.github.com/repos/ONSdigital/design-system/releases/latest | jq -r ".tag_name")

      - run: echo $design_system_release

      #- run: RELEASE_VERSION=$design_system_release yarn cdn-bundle
      #- run: yarn install
      #- run: mkdir ../../dist/$design_system_release
      #- run: cd ../../dist
      #- run: ls

      #- run: zip -r ../../templates/templates.zip templates/*
      #- run: cp -R build/* ../../dist/$design_system_release
      #upload to release
